# Generated by Django 4.1 on 2023-04-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_showdown', '0004_alter_question_difficulty_alter_question_xp_earned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='xp_earned',
        ),
    ]
