# Generated by Django 4.1 on 2023-04-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_showdown', '0005_remove_question_xp_earned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='opt4',
        ),
    ]
