# Generated by Django 4.1 on 2023-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_showdown', '0006_remove_question_opt4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='opt2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
