# Generated by Django 4.1 on 2023-04-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_showdown', '0009_alter_useranswer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['user', 'question_category', 'status']},
        ),
    ]
