# Generated by Django 4.1 on 2023-04-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_showdown', '0010_alter_useranswer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
    ]
